export enum Role {
    ADMIN = 'ADMIN',
    EMPLEADO = 'EMPLEADO',
    CAJERO = 'CAJERO',
    BODEGUERO = 'BODEGUERO',
    SUPERADMIN = 'SUPERADMIN',
    RRHH = 'RRHH',
    COMPRAS = 'COMPRAS',
    VENTAS = 'VENTAS', 
    PENDIENTE = 'PENDIENTE'
}